backend:
  name: github
  repo: test000391.github.io/my-site  # استبدلها باسم المستودع الخاص بك

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "الصفحات"
    files:
      - name: "home"
        label: "الصفحة الرئيسية"
        file: "index.md"  # تأكد من أن هذا هو اسم الملف الذي يحتوي على المحتوى الذي تريد تعديله
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "النص", name: "body", widget: "text" }
