backend:
  name: github
  repo: test000391.github.io/my-site  # استبدل "yourusername/my-site" باسم المستودع الخاص بك
  branch: main  # تأكد من استخدام الفرع الرئيسي

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "الصفحات"
    files:
      - name: "home"
        label: "الصفحة الرئيسية"
        file: "index.md"  # هذا هو الملف الذي سيتم تعديله
        fields:
          - { label: "العنوان", name: "title", widget: "string" }
          - { label: "النص", name: "body", widget: "text" }
